## 前処理05

本ファイルは以下の処理を行うコードである。

1. `/workspace/datasets/statcast-customized/preprocess_04`データセットを読みだす。

2. 必要なカラムをクラスラベルに変換して、`/workspace/datasets/statcast-customized/preprocess_05`に保存する。

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
load_root_path = '/workspace/datasets/statcast-customized-tmp/preprocess_04/'
save_root_path = '/workspace/datasets/statcast-customized-tmp/preprocess_05/'

In [3]:
def get_parquet_file_path_list(load_root_path):
    file_path_list = []
    # Walk through the directory and its subdirectories to find all Parquet files
    for root, dirs, files in os.walk(load_root_path):
        for file in files:
            if file.endswith('.parquet'):
                file_path_list.append(os.path.join(root, file))
    # Sort the file paths to ensure consistent order
    file_path_list.sort()
    return file_path_list

In [4]:
def load_parquet(path: str) -> pd.DataFrame:
    """Read a Parquet file and return a pandas DataFrame."""
    return pd.read_parquet(path)

In [5]:
parquet_file_path_list = get_parquet_file_path_list(load_root_path)
for file_path in parquet_file_path_list:
    print(f'Load: {file_path}')
print(f'Number of Parquet files: {len(parquet_file_path_list)}')

Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2017_11.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_03.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2018_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_03.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2019_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2020_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2020_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2020_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2020_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_03.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2021_11.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_03.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2022_11.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_03.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2023_11.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_03.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2024_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_03.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_04.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_05.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_06.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_07.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_08.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_09.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_10.parquet
Load: /workspace/datasets/statcast-customized-tmp/preprocess_04/statcast_2025_11.parquet
Number of Parquet files: 72

In [6]:
# データの確認
df_one_month = load_parquet(parquet_file_path_list[0])
with pd.option_context('display.max_columns', None, 'display.max_rows', None):
    display(df_one_month.head(20))

,at_bat_id,swing_attempt,swing_result,bb_type,launch_speed,launch_angle,hit_distance_sc,p_throws,pitch_type,release_speed,release_spin_rate,pfx_x,pfx_z,plate_x,plate_z,batter,stand,base_out_state,count_state,inning_clipped,is_inning_top,diff_score_clipped,pitch_number_clipped
0,0,False,None,None,NaN,NaN,NaN,R,FF,94.9,2146.0,-0.78,1.10,0.281634,4.334447,656941,L,0,0,1,True,0,1
1,0,True,foul,None,NaN,NaN,NaN,R,SI,95.9,2144.0,-1.59,0.84,-0.578784,2.324124,656941,L,0,3,1,True,0,2
2,0,False,None,None,NaN,NaN,NaN,R,SI,97.3,2015.0,-1.34,0.55,-0.014284,1.326134,656941,L,0,4,1,True,0,3
3,0,True,hit_into_play,line_drive,96.1,18.0,256.0,R,SL,84.6,2194.0,1.10,-0.17,0.135816,1.943402,656941,L,0,7,1,True,0,4
4,1,False,None,None,NaN,NaN,NaN,R,SI,98.4,2066.0,-1.28,0.68,0.421448,1.833604,592178,R,1,0,1,True,0,1
5,1,False,None,None,NaN,NaN,NaN,R,SI,96.3,2086.0,-1.20,0.68,0.624980,2.677019,592178,R,1,1,1,True,0,2
6,1,False,None,None,NaN,NaN,NaN,R,SL,86.6,2333.0,1.42,0.65,2.357224,1.320178,592178,R,1,4,1,True,0,3
7,1,False,None,None,NaN,NaN,NaN,R,SL,86.1,2261.0,1.08,-0.03,0.263640,1.705923,592178,R,1,7,1,True,0,4
8,1,True,swinging_strike,None,NaN,NaN,NaN,R,FF,99.9,2278.0,-0.85,1.19,-0.540721,3.304990,592178,R,1,8,1,True,0,5
9,2,False,None,None,NaN,NaN,NaN,R,FF,99.3,2144.0,-0.92,1.21,-0.226224,3.970468,519203,L,9,0,1,True,0,1
10,2,True,swinging_strike,None,NaN,NaN,NaN,R,CH,89.9,2221.0,-1.69,0.42,-0.508514,2.091066,519203,L,9,3,1,True,0,2
11,2,True,hit_into_play,line_drive,98.8,16.0,265.0,R,FF,96.9,2174.0,-0.68,0.77,0.646547,2.991425,519203,L,9,4,1,True,0,3
12,3,False,None,None,NaN,NaN,NaN,R,CH,88.8,2034.0,-1.45,0.04,1.300744,0.649932,450314,L,11,0,1,True,0,1
13,3,True,swinging_strike,None,NaN,NaN,NaN,R,CH,88.7,2124.0,-1.53,-0.07,0.388203,1.357201,450314,L,11,3,1,True,0,2
14,3,True,swinging_strike,None,NaN,NaN,NaN,R,CH,89.3,2239.0,-1.45,0.72,0.362064,1.977065,450314,L,11,4,1,True,0,3
15,3,True,hit_into_play,ground_ball,75.7,1.0,56.0,R,FF,98.2,2134.0,-0.66,1.17,0.365069,4.223813,450314,L,11,5,1,True,0,4
16,4,False,None,None,NaN,NaN,NaN,L,FF,91.3,2258.0,0.83,1.22,-0.511407,1.142248,451594,R,0,0,1,False,0,1
17,4,False,None,None,NaN,NaN,NaN,L,SI,89.7,2059.0,1.29,0.77,1.263017,2.426348,451594,R,0,3,1,False,0,2
18,4,True,hit_into_play,line_drive,84.9,23.0,298.0,L,SI,88.2,1951.0,0.98,0.64,-0.039568,1.378717,451594,R,0,6,1,False,0,3
19,5,False,None,None,NaN,NaN,NaN,L,FF,91.1,2314.0,0.57,1.38,-1.388318,2.068034,649557,R,8,0,1,False,0,1

In [7]:
# 全てのCSVファイルを読み込んで1つのDataFrameに結合
df_all = pd.concat(
    [load_parquet(path) for path in parquet_file_path_list],
    ignore_index=True
)
print(df_all.shape)
display(df_all.head())

(5781569, 23)

,at_bat_id,swing_attempt,swing_result,bb_type,launch_speed,launch_angle,hit_distance_sc,p_throws,pitch_type,release_speed,...,plate_x,plate_z,batter,stand,base_out_state,count_state,inning_clipped,is_inning_top,diff_score_clipped,pitch_number_clipped
0,0,False,None,None,NaN,NaN,NaN,R,FF,94.9,...,0.281634,4.334447,656941,L,0,0,1,True,0,1
1,0,True,foul,None,NaN,NaN,NaN,R,SI,95.9,...,-0.578784,2.324124,656941,L,0,3,1,True,0,2
2,0,False,None,None,NaN,NaN,NaN,R,SI,97.3,...,-0.014284,1.326134,656941,L,0,4,1,True,0,3
3,0,True,hit_into_play,line_drive,96.1,18.0,256.0,R,SL,84.6,...,0.135816,1.943402,656941,L,0,7,1,True,0,4
4,1,False,None,None,NaN,NaN,NaN,R,SI,98.4,...,0.421448,1.833604,592178,R,1,0,1,True,0,1

In [8]:
unique_at_bat_id_count = df_all["at_bat_id"].nunique()
print(f"at_bat_id のユニーク数: {unique_at_bat_id_count}")
print(f'最後の at_bat_id: {df_all["at_bat_id"].iloc[-1]}')

at_bat_id のユニーク数: 1493291
最後の at_bat_id: 1493290

In [9]:
from sklearn.model_selection import train_test_split

# at_bat_id でtrain/valid/testに分割して保存

# 全ユニーク at_bat_id を取得
all_at_bat_ids = df_all["at_bat_id"].unique().tolist()
print(f"Total unique at_bat_ids: {len(all_at_bat_ids)}")

# 分割割合
train_ratio = 0.8
valid_ratio = 0.1
test_ratio  = 0.1
SEED = 42

# train / (valid + test) に分割
train_ids, temp_ids = train_test_split(
    all_at_bat_ids,
    test_size=(valid_ratio + test_ratio),
    random_state=SEED
)

# valid / test に分割
valid_ids, test_ids = train_test_split(
    temp_ids,
    test_size=test_ratio / (valid_ratio + test_ratio),
    random_state=SEED
)

print(f"Train: {len(train_ids)} ({len(train_ids)/len(all_at_bat_ids)*100:.1f}%)")
print(f"Valid: {len(valid_ids)} ({len(valid_ids)/len(all_at_bat_ids)*100:.1f}%)")
print(f"Test:  {len(test_ids)} ({len(test_ids)/len(all_at_bat_ids)*100:.1f}%)")

# 保存
split_save_dir = os.path.join(save_root_path, "split")
os.makedirs(split_save_dir, exist_ok=True)

pd.Series(train_ids, name="at_bat_id").to_csv(os.path.join(split_save_dir, "train_at_bat_ids.csv"), index=False)
pd.Series(valid_ids, name="at_bat_id").to_csv(os.path.join(split_save_dir, "valid_at_bat_ids.csv"), index=False)
pd.Series(test_ids,  name="at_bat_id").to_csv(os.path.join(split_save_dir, "test_at_bat_ids.csv"),  index=False)

print(f"Saved split files to: {split_save_dir}")

Total unique at_bat_ids: 1493291
Train: 1194632 (80.0%)
Valid: 149329 (10.0%)
Test:  149330 (10.0%)
Saved split files to: /workspace/datasets/statcast-customized-tmp/preprocess_05/split

In [10]:
def create_class_label_mapping(df: pd.DataFrame, column: str):
    """
    指定カラムのユニーク値とカウント数を集計し、カウント降順でクラスラベルを付与する。

    Returns
    -------
    encoded_df : pd.DataFrame
        指定カラムをクラスラベルに置換したDataFrame
    stats_df : pd.DataFrame
        [class_label, <column>, count] を持つ集計テーブル
    """
    if column not in df.columns:
        raise ValueError(f"'{column}' はDataFrameに存在しません。")

    # NaNを除いて件数集計（降順）
    counts = df[column].value_counts(dropna=True)

    # ユニーク値・件数・クラスラベル対応表
    stats_df = pd.DataFrame({
        column: counts.index,
        "count": counts.values
    })
    stats_df["class_label"] = np.arange(len(stats_df), dtype=int)
    stats_df = stats_df[["class_label", column, "count"]]

    # NaNを安全にマッピング
    sentinel = object()
    src = df[column].astype("object").where(df[column].notna(), sentinel)
    key = stats_df[column].astype("object").where(stats_df[column].notna(), sentinel)

    label_map = pd.Series(stats_df["class_label"].to_numpy(), index=key)
    encoded_col = src.map(label_map).astype("Int64")

    encoded_df = df.copy()
    encoded_df[column] = encoded_col

    return encoded_df, stats_df

In [11]:
encoded_df_swing_result, stats_swing_result = create_class_label_mapping(df_all, "swing_result")
print(stats_swing_result)

   class_label             swing_result    count
0            0                     foul  1018256
1            1            hit_into_play  1016206
2            2          swinging_strike   597528
3            3                 foul_tip    53779
4            4  swinging_strike_blocked    38143
5            5                foul_bunt     8931
6            6              missed_bunt     1532
7            7            bunt_foul_tip      136
8            8            foul_pitchout        2

In [12]:
encoded_df_bb_type, stats_bb_type = create_class_label_mapping(df_all, "bb_type")
print(stats_bb_type)

   class_label      bb_type   count
0            0  ground_ball  438621
1            1     fly_ball  257052
2            2   line_drive  248084
3            3        popup   72374

In [13]:
encoded_df_p_throws, stats_p_throws = create_class_label_mapping(df_all, "p_throws")
print(stats_p_throws)

   class_label p_throws    count
0            0        R  4203883
1            1        L  1577686

In [14]:
encoded_df_stand, stats_stand = create_class_label_mapping(df_all, "stand")
print(stats_stand)

   class_label stand    count
0            0     R  3349375
1            1     L  2432194

In [15]:
encoded_df_pitch_type, stats_pitch_type = create_class_label_mapping(df_all, "pitch_type")
print(stats_pitch_type)

    class_label pitch_type    count
0             0         FF  1913606
1             1         SI   943458
2             2         SL   910759
3             3         CH   608778
4             4         CU   414358
5             5         FC   406039
6             6         ST   196678
7             7         KC   132750
8             8         FS   118214
9             9         SV    21418
10           10         FA     4969
11           11         KN     4637
12           12         EP     2812
13           13         FO     1706
14           14         CS      978
15           15         PO      473
16           16         SC      331
17           17         UN        7

In [16]:
encoded_df_batter, stats_batter = create_class_label_mapping(df_all, "batter")
print(stats_batter.head())
print(f"len(stats_batter): {len(stats_batter)}")

   class_label  batter  count
0            0  608070  23649
1            1  596019  23609
2            2  502671  23607
3            3  518692  23416
4            4  656941  23300
len(stats_batter): 783

In [17]:
# これまで作成した stats_* を一括で整理
stats_tables = {
    "swing_result": stats_swing_result.copy(),
    "bb_type": stats_bb_type.copy(),
    "p_throws": stats_p_throws.copy(),
    "stand": stats_stand.copy(),
    "pitch_type": stats_pitch_type.copy(),
    "batter": stats_batter.copy(),
}

# 共通フォーマットに統一して縦結合
stats_long_list = []
for feature_name, stats_df in stats_tables.items():
    value_col = [c for c in stats_df.columns if c not in ["class_label", "count"]][0]
    tmp = stats_df.rename(columns={value_col: "value"}).copy()
    tmp.insert(0, "feature", feature_name)
    stats_long_list.append(tmp[["feature", "class_label", "value", "count"]])

stats_all = pd.concat(stats_long_list, ignore_index=True)

print("stats_all shape:", stats_all.shape)
display(stats_all.head(20))

# 保存
stats_save_dir = os.path.join(save_root_path, "stats")
os.makedirs(stats_save_dir, exist_ok=True)

for feature_name, stats_df in stats_tables.items():
    stats_df.to_csv(os.path.join(stats_save_dir, f"stats_{feature_name}.csv"), index=False)

stats_all.to_csv(os.path.join(stats_save_dir, "stats_all.csv"), index=False)
print(f"Saved: {stats_save_dir}")

stats_all shape: (818, 4)

         feature  class_label                    value    count
0   swing_result            0                     foul  1018256
1   swing_result            1            hit_into_play  1016206
2   swing_result            2          swinging_strike   597528
3   swing_result            3                 foul_tip    53779
4   swing_result            4  swinging_strike_blocked    38143
5   swing_result            5                foul_bunt     8931
6   swing_result            6              missed_bunt     1532
7   swing_result            7            bunt_foul_tip      136
8   swing_result            8            foul_pitchout        2
9        bb_type            0              ground_ball   438621
10       bb_type            1                 fly_ball   257052
11       bb_type            2               line_drive   248084
12       bb_type            3                    popup    72374
13      p_throws            0                        R  4203883
14      p_throws            1                        L  1577686
15         stand            0                        R  3349375
16         stand            1                        L  2432194
17    pitch_type            0                       FF  1913606
18    pitch_type            1                       SI   943458
19    pitch_type            2                       SL   910759

Saved: /workspace/datasets/statcast-customized-tmp/preprocess_05/stats

In [18]:
def encode_features_with_stats_all(df: pd.DataFrame) -> pd.DataFrame:
    """
    df内の以下カラムを、stats_allの対応表を使ってクラスラベル（Int64）に置換したDataFrameを返す。
    - swing_result
    - bb_type
    - p_throws
    - stand
    - pitch_type
    - batter
    """
    target_features = ["swing_result", "bb_type", "p_throws", "stand", "pitch_type", "batter"]

    missing_cols = [c for c in target_features if c not in df.columns]
    if missing_cols:
        raise ValueError(f"dfに必要なカラムがありません: {missing_cols}")

    encoded_df = df.copy()
    sentinel = object()

    for feature in target_features:
        map_df = stats_all.loc[stats_all["feature"] == feature, ["value", "class_label"]].copy()
        if map_df.empty:
            raise ValueError(f"stats_allにfeature='{feature}'の定義がありません。")

        # 重複があれば先頭を採用
        map_df = map_df.drop_duplicates(subset=["value"], keep="first")

        key = map_df["value"].astype("object").where(map_df["value"].notna(), sentinel)
        label_map = pd.Series(map_df["class_label"].to_numpy(), index=key)

        src = encoded_df[feature].astype("object").where(encoded_df[feature].notna(), sentinel)
        encoded_df[feature] = src.map(label_map).astype("Int64")

    return encoded_df

In [19]:
def count_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """
    各カラムの欠損値数（NaN / <NA>）を集計して返す。
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("df must be a pandas DataFrame")

    missing_counts = df.isna().sum()

    result = (
        missing_counts.rename("missing_count")
        .reset_index()
        .rename(columns={"index": "column"})
    )
    return result

In [20]:
# 実験
df_one_month_encoded = encode_features_with_stats_all(df_one_month)
with pd.option_context('display.max_columns', None, 'display.max_rows', None):
    display(df_one_month_encoded.head(20))

,at_bat_id,swing_attempt,swing_result,bb_type,launch_speed,launch_angle,hit_distance_sc,p_throws,pitch_type,release_speed,release_spin_rate,pfx_x,pfx_z,plate_x,plate_z,batter,stand,base_out_state,count_state,inning_clipped,is_inning_top,diff_score_clipped,pitch_number_clipped
0,0,False,<NA>,<NA>,NaN,NaN,NaN,0,0,94.9,2146.0,-0.78,1.10,0.281634,4.334447,4,1,0,0,1,True,0,1
1,0,True,0,<NA>,NaN,NaN,NaN,0,1,95.9,2144.0,-1.59,0.84,-0.578784,2.324124,4,1,0,3,1,True,0,2
2,0,False,<NA>,<NA>,NaN,NaN,NaN,0,1,97.3,2015.0,-1.34,0.55,-0.014284,1.326134,4,1,0,4,1,True,0,3
3,0,True,1,2,96.1,18.0,256.0,0,2,84.6,2194.0,1.10,-0.17,0.135816,1.943402,4,1,0,7,1,True,0,4
4,1,False,<NA>,<NA>,NaN,NaN,NaN,0,1,98.4,2066.0,-1.28,0.68,0.421448,1.833604,110,0,1,0,1,True,0,1
5,1,False,<NA>,<NA>,NaN,NaN,NaN,0,1,96.3,2086.0,-1.20,0.68,0.624980,2.677019,110,0,1,1,1,True,0,2
6,1,False,<NA>,<NA>,NaN,NaN,NaN,0,2,86.6,2333.0,1.42,0.65,2.357224,1.320178,110,0,1,4,1,True,0,3
7,1,False,<NA>,<NA>,NaN,NaN,NaN,0,2,86.1,2261.0,1.08,-0.03,0.263640,1.705923,110,0,1,7,1,True,0,4
8,1,True,2,<NA>,NaN,NaN,NaN,0,0,99.9,2278.0,-0.85,1.19,-0.540721,3.304990,110,0,1,8,1,True,0,5
9,2,False,<NA>,<NA>,NaN,NaN,NaN,0,0,99.3,2144.0,-0.92,1.21,-0.226224,3.970468,53,1,9,0,1,True,0,1
10,2,True,2,<NA>,NaN,NaN,NaN,0,3,89.9,2221.0,-1.69,0.42,-0.508514,2.091066,53,1,9,3,1,True,0,2
11,2,True,1,2,98.8,16.0,265.0,0,0,96.9,2174.0,-0.68,0.77,0.646547,2.991425,53,1,9,4,1,True,0,3
12,3,False,<NA>,<NA>,NaN,NaN,NaN,0,3,88.8,2034.0,-1.45,0.04,1.300744,0.649932,451,1,11,0,1,True,0,1
13,3,True,2,<NA>,NaN,NaN,NaN,0,3,88.7,2124.0,-1.53,-0.07,0.388203,1.357201,451,1,11,3,1,True,0,2
14,3,True,2,<NA>,NaN,NaN,NaN,0,3,89.3,2239.0,-1.45,0.72,0.362064,1.977065,451,1,11,4,1,True,0,3
15,3,True,1,0,75.7,1.0,56.0,0,0,98.2,2134.0,-0.66,1.17,0.365069,4.223813,451,1,11,5,1,True,0,4
16,4,False,<NA>,<NA>,NaN,NaN,NaN,1,0,91.3,2258.0,0.83,1.22,-0.511407,1.142248,341,0,0,0,1,False,0,1
17,4,False,<NA>,<NA>,NaN,NaN,NaN,1,1,89.7,2059.0,1.29,0.77,1.263017,2.426348,341,0,0,3,1,False,0,2
18,4,True,1,2,84.9,23.0,298.0,1,1,88.2,1951.0,0.98,0.64,-0.039568,1.378717,341,0,0,6,1,False,0,3
19,5,False,<NA>,<NA>,NaN,NaN,NaN,1,0,91.1,2314.0,0.57,1.38,-1.388318,2.068034,286,0,8,0,1,False,0,1

In [21]:
# NaNの数をカウント
missing_counts = count_missing_values(df_one_month_encoded)
print(missing_counts)

                  column  missing_count
0              at_bat_id              0
1          swing_attempt              0
2           swing_result          48171
3                bb_type          73112
4           launch_speed          65007
5           launch_angle          65006
6        hit_distance_sc          66879
7               p_throws              0
8             pitch_type           1328
9          release_speed           1258
10     release_spin_rate           3458
11                 pfx_x           1262
12                 pfx_z           1262
13               plate_x           1328
14               plate_z           1328
15                batter              0
16                 stand              0
17        base_out_state              0
18           count_state              0
19        inning_clipped              0
20         is_inning_top              0
21    diff_score_clipped              0
22  pitch_number_clipped              0

In [22]:
def get_features_and_save_parquet(parquet_file_path, save_root_path):
    df = load_parquet(parquet_file_path)
    df_with_features = encode_features_with_stats_all(df)

    # Create the save path by replacing the load root with the save root
    relative_path = os.path.relpath(parquet_file_path, load_root_path).replace('.parquet', '.parquet')
    save_path = os.path.join(save_root_path, relative_path)

    # Ensure the directory exists
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    # Save the extracted DataFrame to a new Parquet file
    df_with_features.to_parquet(save_path, index=False)
    print(f'Saved extracted data to: {save_path}')

In [23]:
for parquet_file_path in parquet_file_path_list:
    get_features_and_save_parquet(parquet_file_path, save_root_path)

Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2017_11.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_03.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2018_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_03.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2019_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2020_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2020_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2020_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2020_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_03.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2021_11.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_03.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2022_11.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_03.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2023_11.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_03.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2024_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_03.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_04.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_05.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_06.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_07.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_08.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_09.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_10.parquet
Saved extracted data to: /workspace/datasets/statcast-customized-tmp/preprocess_05/statcast_2025_11.parquet